-- Role hierarchy: rename BENEVOLE → VOLUNTEER, add SUPER_ADMIN, USER
ALTER TYPE "Role" RENAME VALUE 'BENEVOLE' TO 'VOLUNTEER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'USER';

-- Update default
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'VOLUNTEER'::"Role";
