packages: []
allowBuilds:
  "@prisma/engines": true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - find-my-way@9.6.1
overrides:
  "postcss@<8.5.23": ">=8.5.23"
  "valibot@<1.4.2": ">=1.4.2"
  "fast-uri@<3.1.5": ">=3.1.5"
  "find-my-way@<=9.6.0": ">=9.6.1"
  "brace-expansion@>=5.0.0 <5.0.9": ">=5.0.9"
