export type UserRole = "ADMIN" | "BENEVOLE";
export type UserStatus = "ACTIF" | "INACTIF";

export type User = {
  id: number;
  nom: string;
  prenom: string;
  email: string;
  telephone: string;
  role: UserRole;
  statut: UserStatus;
  date_entree: string;
  derniere_activite: string;
  total_heures: number;
  nb_presences: number;
};

export const users: User[] = [
  {
    id: 1,
    nom: "Dupont",
    prenom: "Marie",
    email: "marie.dupont@asso.fr",
    telephone: "06 12 34 56 78",
    role: "ADMIN",
    statut: "ACTIF",
    date_entree: "2026-01-12",
    derniere_activite: "2026-08-18",
    total_heures: 45,
    nb_presences: 12,
  },
  {
    id: 2,
    nom: "Martin",
    prenom: "Jean",
    email: "jean.martin@asso.fr",
    telephone: "06 23 45 67 89",
    role: "BENEVOLE",
    statut: "ACTIF",
    date_entree: "2026-02-03",
    derniere_activite: "2026-08-18",
    total_heures: 120,
    nb_presences: 30,
  },
  {
    id: 3,
    nom: "Bernard",
    prenom: "Sophie",
    email: "sophie.bernard@asso.fr",
    telephone: "06 34 56 78 90",
    role: "BENEVOLE",
    statut: "ACTIF",
    date_entree: "2026-02-20",
    derniere_activite: "2026-08-18",
    total_heures: 86,
    nb_presences: 24,
  },
  {
    id: 4,
    nom: "Lefevre",
    prenom: "Pierre",
    email: "pierre.lefevre@asso.fr",
    telephone: "06 45 67 89 01",
    role: "BENEVOLE",
    statut: "INACTIF",
    date_entree: "2026-03-08",
    derniere_activite: "2026-06-30",
    total_heures: 52,
    nb_presences: 14,
  },
  {
    id: 5,
    nom: "Morel",
    prenom: "Claire",
    email: "claire.morel@asso.fr",
    telephone: "06 56 78 90 12",
    role: "BENEVOLE",
    statut: "ACTIF",
    date_entree: "2026-03-15",
    derniere_activite: "2026-08-17",
    total_heures: 64,
    nb_presences: 18,
  },
  {
    id: 6,
    nom: "Petit",
    prenom: "Luc",
    email: "luc.petit@asso.fr",
    telephone: "06 67 89 01 23",
    role: "ADMIN",
    statut: "ACTIF",
    date_entree: "2026-04-01",
    derniere_activite: "2026-08-16",
    total_heures: 38,
    nb_presences: 10,
  },
  {
    id: 7,
    nom: "Roux",
    prenom: "Amélie",
    email: "amelie.roux@asso.fr",
    telephone: "06 78 90 12 34",
    role: "BENEVOLE",
    statut: "ACTIF",
    date_entree: "2026-04-12",
    derniere_activite: "2026-08-15",
    total_heures: 71,
    nb_presences: 20,
  },
  {
    id: 8,
    nom: "Girard",
    prenom: "Hugo",
    email: "hugo.girard@asso.fr",
    telephone: "06 89 01 23 45",
    role: "BENEVOLE",
    statut: "INACTIF",
    date_entree: "2026-05-05",
    derniere_activite: "2026-07-10",
    total_heures: 22,
    nb_presences: 6,
  },
  {
    id: 9,
    nom: "Bonnet",
    prenom: "Léa",
    email: "lea.bonnet@asso.fr",
    telephone: "06 90 12 34 56",
    role: "BENEVOLE",
    statut: "ACTIF",
    date_entree: "2026-05-22",
    derniere_activite: "2026-08-14",
    total_heures: 47,
    nb_presences: 13,
  },
  {
    id: 10,
    nom: "Faure",
    prenom: "Nathan",
    email: "nathan.faure@asso.fr",
    telephone: "07 12 34 56 78",
    role: "BENEVOLE",
    statut: "ACTIF",
    date_entree: "2026-06-09",
    derniere_activite: "2026-08-13",
    total_heures: 35,
    nb_presences: 9,
  },
  {
    id: 11,
    nom: "Lambert",
    prenom: "Emma",
    email: "emma.lambert@asso.fr",
    telephone: "07 23 45 67 89",
    role: "BENEVOLE",
    statut: "ACTIF",
    date_entree: "2026-06-25",
    derniere_activite: "2026-08-12",
    total_heures: 29,
    nb_presences: 8,
  },
  {
    id: 12,
    nom: "Mercier",
    prenom: "Thomas",
    email: "thomas.mercier@asso.fr",
    telephone: "07 34 56 78 90",
    role: "BENEVOLE",
    statut: "INACTIF",
    date_entree: "2026-07-14",
    derniere_activite: "2026-07-28",
    total_heures: 12,
    nb_presences: 3,
  },
];
